language: perl

matrix:
  include:
  - perl: "5.30"

before_install:
  cpanm -n Devel::Cover::Report::Coveralls

script:
  perl Build.PL && ./Build build && cover -test +ignore Build.pm -report coveralls
