#!/usr/bin/perl

BEGIN {
  $^W = 1;  # Use warnings
  my $start_dir = '/home/dave/src/AudioFile-Info-Ogg-Vorbis-Header-PurePerl';
  chdir($start_dir) or die "Cannot chdir to $start_dir: $!";
  @INC = 
    (
     '/home/dave/src/AudioFile-Info-Ogg-Vorbis-Header-PurePerl/lib',
     '/usr/lib/perl5/5.8.0/i386-linux-thread-multi',
     '/usr/lib/perl5/5.8.0',
     '/usr/lib/perl5/site_perl/5.8.0/i386-linux-thread-multi',
     '/usr/lib/perl5/site_perl/5.8.0',
     '/usr/lib/perl5/site_perl',
     '/usr/lib/perl5/vendor_perl/5.8.0/i386-linux-thread-multi',
     '/usr/lib/perl5/vendor_perl/5.8.0',
     '/usr/lib/perl5/vendor_perl',
     '/home/dave/src/AudioFile-Info-Ogg-Vorbis-Header-PurePerl'
    );
}

use AudioFile::Info::Build;

# This should have just enough arguments to be able to bootstrap the rest.
my $build = resume AudioFile::Info::Build (
  properties => {
    config_dir => '/home/dave/src/AudioFile-Info-Ogg-Vorbis-Header-PurePerl/_build',
  },
);

$build->dispatch;
